-- NOTICE 공통 공지사항 기능 반영 SQL
-- 운영 DB에 NOTICE_TYPE 컬럼이 없을 때 먼저 실행한다.

ALTER TABLE NOTICE ADD NOTICE_TYPE VARCHAR2(20) DEFAULT 'NOTICE' NOT NULL;

UPDATE NOTICE
SET NOTICE_TYPE = 'NOTICE'
WHERE NOTICE_TYPE IS NULL;

ALTER TABLE NOTICE ADD CONSTRAINT CK_NOTICE_TYPE
CHECK (NOTICE_TYPE IN ('NOTICE', 'URGENT', 'UPDATE'));

CREATE INDEX IDX_NOTICE_SEARCH
ON NOTICE (NOTICE_TYPE, NOTICE_ADDDATE DESC, NOTICE_NO DESC);

COMMENT ON COLUMN NOTICE.NOTICE_TYPE IS '공지 분류: NOTICE=공지, URGENT=긴급, UPDATE=업데이트';
